package models

type AutoGenerated struct {
	Feed struct {
		Author struct {
			Name struct {
				Label string `json:"label"`
			} `json:"name"`
			URI struct {
				Label string `json:"label"`
			} `json:"uri"`
		} `json:"author"`
		Entry []struct {
			ImName struct {
				Label string `json:"label"`
			} `json:"im:name,omitempty"`
			Rights struct {
				Label string `json:"label"`
			} `json:"rights,omitempty"`
			ImPrice struct {
				Label string `json:"label"`
				Attributes struct {
					Amount string `json:"amount"`
					Currency string `json:"currency"`
				} `json:"attributes"`
			} `json:"im:price,omitempty"`
			ImImage []struct {
				Label string `json:"label"`
				Attributes struct {
					Height string `json:"height"`
				} `json:"attributes"`
			} `json:"im:image,omitempty"`
			ImArtist struct {
				Label string `json:"label"`
				Attributes struct {
					Href string `json:"href"`
				} `json:"attributes"`
			} `json:"im:artist,omitempty"`
			Title struct {
				Label string `json:"label"`
			} `json:"title"`
			Link struct {
				Attributes struct {
					Rel string `json:"rel"`
					Type string `json:"type"`
					Href string `json:"href"`
				} `json:"attributes"`
			} `json:"link"`
			ID struct {
				Label string `json:"label"`
				Attributes struct {
					ImID string `json:"im:id"`
					ImBundleID string `json:"im:bundleId"`
				} `json:"attributes"`
			} `json:"id"`
			ImContentType struct {
				Attributes struct {
					Term string `json:"term"`
					Label string `json:"label"`
				} `json:"attributes"`
			} `json:"im:contentType"`
			Category struct {
				Attributes struct {
					ImID string `json:"im:id"`
					Term string `json:"term"`
					Scheme string `json:"scheme"`
					Label string `json:"label"`
				} `json:"attributes"`
			} `json:"category,omitempty"`
			ImReleaseDate struct {
				Label string `json:"label"`
				Attributes struct {
					Label string `json:"label"`
				} `json:"attributes"`
			} `json:"im:releaseDate,omitempty"`
			Author struct {
				URI struct {
					Label string `json:"label"`
				} `json:"uri"`
				Name struct {
					Label string `json:"label"`
				} `json:"name"`
				Label string `json:"label"`
			} `json:"author,omitempty"`
			ImVersion struct {
				Label string `json:"label"`
			} `json:"im:version,omitempty"`
			ImRating struct {
				Label string `json:"label"`
			} `json:"im:rating,omitempty"`
			Content struct {
				Label string `json:"label"`
				Attributes struct {
					Type string `json:"type"`
				} `json:"attributes"`
			} `json:"content,omitempty"`
			ImVoteSum struct {
				Label string `json:"label"`
			} `json:"im:voteSum,omitempty"`
			ImVoteCount struct {
				Label string `json:"label"`
			} `json:"im:voteCount,omitempty"`
		} `json:"entry"`
		Updated struct {
			Label string `json:"label"`
		} `json:"updated"`
		Rights struct {
			Label string `json:"label"`
		} `json:"rights"`
		Title struct {
			Label string `json:"label"`
		} `json:"title"`
		Icon struct {
			Label string `json:"label"`
		} `json:"icon"`
		Link []struct {
			Attributes struct {
				Rel string `json:"rel"`
				Type string `json:"type"`
				Href string `json:"href"`
			} `json:"attributes"`
		} `json:"link"`
		ID struct {
			Label string `json:"label"`
		} `json:"id"`
	} `json:"feed"`
}
